apiVersion: v1
kind: Secret
metadata:
  name: demo-api-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab
  SPRING_DATASOURCE_USERNAME: lab
  SPRING_DATASOURCE_PASSWORD: lab
