apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-api-config
  namespace: {{ .Values.namespace }}
data:
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redisHost | quote }}
  SPRING_DATA_REDIS_PORT: "6379"
  SERVICE_NAME: {{ .Values.config.serviceName | quote }}
  LAB_SLOW_SECONDS: {{ .Values.config.slowSeconds | quote }}
